EMOTIONS = [
    "fear",
    "anxiety",
    "anger",
    "sadness",
    "grief",
    "loneliness",
    "guilt",
    "jealousy",
    "confusion",
    "hopelessness",
    "lack_of_purpose",
    "stress",
    "frustration",
    "self_doubt",
    "overwhelm",
    "confidence",
    "acceptance",
]

THEMES = [
    "duty",
    "courage",
    "leadership",
    "self_control",
    "compassion",
    "detachment",
    "purpose",
    "forgiveness",
    "service",
    "discipline",
    "resilience",
    "truth",
    "faith",
    "surrender",
    "knowledge",
    "action",
    "patience",
    "humility",
    "self_belief",
    "ethics",
]

CATEGORIES = [
    "career",
    "relationships",
    "mental_health",
    "purpose",
    "ethics",
    "leadership",
    "education",
    "family",
    "spirituality",
    "health",
]

CHARACTERS = [
    "Krishna",
    "Arjuna",
    "Rama",
    "Sita",
    "Hanuman",
    "Ravana",
    "Lakshmana",
    "Bharata",
    "Dasharatha",
]
